## Gather

In [1]:
import pandas as pd
patients = pd.read_csv('./auralin_dataset/patients.csv')
treatments = pd.read_csv('./auralin_dataset/treatments.csv')
adverse_reactions = pd.read_csv('./auralin_dataset/adverse_reactions.csv')

## Assess

In [2]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
patient_id      503 non-null int64
assigned_sex    503 non-null object
given_name      503 non-null object
surname         503 non-null object
address         491 non-null object
city            491 non-null object
state           491 non-null object
zip_code        491 non-null float64
country         491 non-null object
contact         491 non-null object
birthdate       503 non-null object
weight          503 non-null float64
height          503 non-null int64
bmi             503 non-null float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [3]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
given_name      280 non-null object
surname         280 non-null object
auralin         280 non-null object
novodra         280 non-null object
hba1c_start     280 non-null float64
hba1c_end       280 non-null float64
hba1c_change    171 non-null float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [4]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
given_name          34 non-null object
surname             34 non-null object
adverse_reaction    34 non-null object
dtypes: object(3)
memory usage: 896.0+ bytes

In [9]:
# list all

# create a series object out of all the columns and list the duplicates

all_cols = pd.Series(list(patients) + list(treatments) + list(adverse_reactions))

all_cols[all_cols.duplicated()]

14    given_name
15       surname
21    given_name
22       surname
dtype: object

In [10]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [11]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [13]:
patients[patients.address.duplicated()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
282,283,female,Sandy,Taylor,2476 Fulton Street,Rainelle,WV,25962.0,United States,304-438-2648SandraCTaylor@dayrep.com,10/23/1960,206.1,64,35.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [14]:
# sort the values of weight, look for extreme / incorrect values

patients.weight.sort_values()
# looks like we have weights

210     48.8
459    102.1
335    102.7
74     103.2
317    106.0
171    106.5
51     107.1
270    108.1
198    108.5
48     109.1
478    109.6
141    110.2
38     111.8
438    112.0
14     112.0
235    112.2
307    112.4
191    112.6
408    113.1
49     113.3
326    114.0
338    114.1
253    117.0
321    118.4
168    118.8
1      118.8
350    119.0
207    119.2
265    120.0
341    120.3
       ...
332    224.0
252    224.2
12     224.2
222    224.8
166    225.3
111    225.9
101    226.2
150    226.6
352    227.7
428    227.7
88     227.7
13     228.4
339    229.0
182    230.3
121    230.8
257    231.7
395    231.9
246    232.1
219    237.8
11     238.7
50     238.9
441    239.1
499    239.6
439    242.0
487    242.4
144    244.9
61     244.9
283    245.5
118    254.5
485    255.9
Name: weight, Length: 503, dtype: float64

In [15]:
# Zaitseva has a weight of 48
patients[patients['surname']=='Zaitseva']

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [16]:
sum(treatments.auralin.isnull())

0

In [17]:
sum(treatments.novodra.isnull())

0

# Clean

In [18]:
patients_clean = patients.copy()
treatments_clean = treatments.copy()
adverse_reactions_clean = adverse_reactions.copy()

## Missing Data

### Missing Data : Treatments table

### define
There should be 350 rows in the treatments table however there are only 280, the missing values are in treatments_cut.csv

In [19]:
treatments_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
given_name      280 non-null object
surname         280 non-null object
auralin         280 non-null object
novodra         280 non-null object
hba1c_start     280 non-null float64
hba1c_end       280 non-null float64
hba1c_change    171 non-null float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [21]:
treatment_cut = pd.read_csv('./auralin_dataset/treatments_cut.csv')
treatment_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

join the 2 datasets together, using concatenate
### code

In [22]:
treatments_clean_full = pd.concat([treatments_clean, treatment_cut])

### test

In [25]:
treatments_clean_full.count()

given_name      350
surname         350
auralin         350
novodra         350
hba1c_start     350
hba1c_end       350
hba1c_change    213
dtype: int64

### Missing Data : Missing HbA1c changes and Inaccurate HbA1c changes (leading 4s mistaken as 9s)

Missing data in the hba1c_change column, this is calculated from hba1c_start and hba1c_end

### Test

In [43]:
# 109 rows contain NaN 
treatments[treatments['hba1c_change'].isnull()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
12,roxanne,andreyeva,29u - 38u,-,9.54,9.14,NaN
14,simone,baumgaertner,27u - 37u,-,7.74,7.30,NaN
15,enco,žibrik,55u - 68u,-,7.78,7.34,NaN
16,camilla,zaitseva,28u - 37u,-,7.53,7.13,NaN
18,addolorata,lombardi,-,49u - 46u,7.75,7.33,NaN
19,khalid,johnsrud,-,54u - 54u,8.35,7.94,NaN
22,brancaleone,russo,53u - 60u,-,8.61,8.18,NaN
23,chiemela,tobeolisa,-,43u - 47u,7.59,7.17,NaN
31,bao,she,-,48u - 45u,9.09,8.62,NaN
33,cannan,cabrera,-,40u - 31u,7.94,7.58,NaN
34,alexander,mathiesen,47u - 58u,-,7.96,7.55,NaN
36,chỉ,lâm,45u - 48u,-,7.68,7.24,NaN
37,władysław,wieczorek,24u - 37u,-,7.92,7.47,NaN
45,zdeněk,synek,-,31u - 31u,7.67,7.32,NaN
47,jad allah,gaber,-,38u - 41u,7.97,7.52,NaN
48,zak,kelly,-,38u - 38u,7.66,7.26,NaN
50,albinca,komavec,-,41u - 39u,7.89,7.46,NaN
51,kristoffer,martinsen,29u - 37u,-,9.18,8.64,NaN
52,mỹ,quynh,57u - 64u,-,7.61,7.16,NaN
54,oles,zhdanov,54u - 67u,-,7.52,7.11,NaN
58,gabryŝ,tomaszewski,29u - 37u,-,7.87,7.47,NaN
59,leixandre,alanis,61u - 67u,-,7.74,7.32,NaN
60,onyekachukwu,obinna,37u - 46u,-,7.58,7.12,NaN
62,hanka,gegič,-,19u - 27u,7.67,7.29,NaN
68,fatimah,kinfe,-,43u - 42u,7.88,7.56,NaN
...,...,...,...,...,...,...,...
204,maximus,henzen,49u - 55u,-,7.79,7.34,NaN
205,najla,touma,-,39u - 44u,7.66,7.31,NaN
208,katrine,lynge,-,43u - 42u,7.60,7.13,NaN
209,kári,hervinsson,37u - 43u,-,8.09,7.66,NaN
210,vanessa,ferguson,39u - 50u,-,7.97,7.58,NaN
211,nương,vũ,31u - 38u,-,7.68,7.29,NaN
216,þórunn,tryggvadóttir,-,30u - 32u,7.98,7.51,NaN
218,sirkka,piirainen,-,26u - 24u,8.90,8.59,NaN
224,cintia,csorba,47u - 50u,-,8.49,8.00,NaN
230,eric,ek,-,51u - 47u,7.92,7.47,NaN
235,eemil,laine,-,30u - 29u,7.89,7.53,NaN
238,anja,hueber,-,31u - 32u,8.82,8.36,NaN
240,rocco,christie,-,42u - 40u,7.96,7.62,NaN
241,elisabetta,lorenzo,-,28u - 24u,7.78,7.42,NaN
242,fareeq,kalb,-,51u - 54u,7.97,7.59,NaN
244,angel,grant,31u - 37u,-,7.93,7.47,NaN
246,tomáš,navrátil,24u - 36u,-,7.84,7.41,NaN
247,johanna,dreher,51u - 59u,-,7.77,7.34,NaN
248,brianna,lansell,39u - 47u,-,9.48,9.06,NaN
251,aksel,vestergaard,-,42u - 38u,9.62,9.29,NaN
253,albino,schiavone,35u - 43u,-,7.56,7.15,NaN
254,jose,combs,-,39u - 36u,7.89,7.42,NaN
258,csilla,herczegh,-,43u - 46u,7.71,7.27,NaN
260,david,beauvais,-,26u - 23u,7.87,7.47,NaN
261,caroline,shuler,-,50u - 54u,7.63,7.27,NaN
269,hiromu,horikawa,-,47u - 46u,7.77,7.28,NaN
271,leo,vieira,-,30u - 33u,7.74,7.36,NaN
273,kate,wilkinson,36u - 39u,-,7.72,7.20,NaN
274,naja,enoksen,43u - 50u,-,7.98,7.59,NaN
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN

### Define

recalc all the values again to fill in the NaN values

### Code

In [45]:
treatments_clean_full['hba1c_change'] = treatments_clean_full['hba1c_start'] - treatments_clean_full['hba1c_end']

In [46]:
treatments_clean_full

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
5,jasmine,sykes,-,42u - 44u,7.56,7.18,0.38
6,sophia,haugen,37u - 42u,-,7.65,7.27,0.38
7,eddie,archer,31u - 38u,-,7.89,7.55,0.34
8,saber,ménard,-,54u - 54u,8.08,7.70,0.38
9,asia,woźniak,30u - 36u,-,7.76,7.37,0.39
10,joseph,day,29u - 36u,-,7.70,7.19,0.51
11,kristiina,hyypiä,-,36u - 38u,7.87,7.49,0.38
12,roxanne,andreyeva,29u - 38u,-,9.54,9.14,0.40
13,gregor,bole,-,47u - 45u,7.61,7.16,0.45
14,simone,baumgaertner,27u - 37u,-,7.74,7.30,0.44
15,enco,žibrik,55u - 68u,-,7.78,7.34,0.44
16,camilla,zaitseva,28u - 37u,-,7.53,7.13,0.40
17,gina,cain,-,36u - 36u,7.88,7.40,0.48
18,addolorata,lombardi,-,49u - 46u,7.75,7.33,0.42
19,khalid,johnsrud,-,54u - 54u,8.35,7.94,0.41
20,mile,stanić,-,47u - 48u,7.66,7.24,0.42
21,tekla,walczak,29u - 39u,-,7.61,7.29,0.32
22,brancaleone,russo,53u - 60u,-,8.61,8.18,0.43
23,chiemela,tobeolisa,-,43u - 47u,7.59,7.17,0.42
24,isac,berg,31u - 41u,-,9.68,9.29,0.39
25,benoît,bonami,-,44u - 43u,9.82,9.40,0.42
26,suhaim,rahal,-,49u - 47u,7.94,7.50,0.44
27,mizuki,iwata,-,45u - 46u,7.70,7.23,0.47
28,clinton,miller,42u - 51u,-,7.79,7.40,0.39
29,eugene,mironov,42u - 49u,-,7.81,7.48,0.33
...,...,...,...,...,...,...,...
40,eufemio,rosario,-,37u - 40u,7.54,7.26,0.28
41,dalmacia,madrid,-,26u - 23u,7.67,7.21,0.46
42,daimy,tromp,-,40u - 45u,9.41,8.94,0.47
43,hans peter,radislav,42u - 53u,-,7.60,7.20,0.40
44,jeremy,montagu,-,52u - 52u,7.68,7.36,0.32
45,štefanija,novosel,37u - 42u,-,7.64,7.17,0.47
46,anja,mueller,43u - 56u,-,7.58,7.29,0.29
47,regolo,nucci,51u - 59u,-,7.53,7.02,0.51
48,nebechi,ekechukwu,-,37u - 39u,7.78,7.39,0.39
49,satsita,batukayev,-,42u - 42u,7.63,7.25,0.38
50,timothy,cotton,-,26u - 25u,7.92,7.52,0.40
51,bjørnar,nilsen,-,36u - 33u,7.99,7.70,0.29
52,vivien,zsinkó,30u - 38u,-,8.35,7.92,0.43
53,genet,fesahaye,25u - 35u,-,7.73,7.36,0.37
54,borna,šlezinger,-,42u - 41u,7.55,7.18,0.37
55,mary,adams,-,32u - 33u,7.65,7.26,0.39
56,blanka,jurković,31u - 43u,-,7.77,7.33,0.44
57,joseph,tucker,48u - 56u,-,7.67,7.30,0.37
58,christopher,woodward,-,55u - 51u,7.51,7.06,0.45
59,robert,maslov,55u - 68u,-,7.65,7.35,0.30
60,maret,sultygov,-,26u - 23u,7.67,7.30,0.37
61,ella,lund,38u - 47u,-,7.57,7.21,0.36
62,fakhri,fakhoury,39u - 50u,-,7.83,7.39,0.44
63,žarka,rap,35u - 48u,-,7.54,7.15,0.39
64,lixue,hsueh,-,22u - 23u,9.21,8.80,0.41
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

## Tidiness Data

### Missing Data : Contact column in patients table contains two variables: phone number and email

In [60]:
patients_clean.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

### Define

- split the contact column, it contains both

In [90]:
patients_clean['email'] = patients_clean['contact'].str.extract('([a-zA-Z][a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+[a-zA-Z])')
patients_clean['phone_number'] = patients_clean.contact.str.extract('((?:\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})', expand=True)

C:\tools\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.

In [85]:
patients_clean

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,email,phone_number
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6,9170ZoeWellish@superrito.com,951-719-9170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2,PamelaSHill@cuvox.de,+1 (217) 569-3204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8,6804JaeMDebord@gustr.com,402-363-6804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7,PhanBaLiem@jourrapide.com,+1 (732) 636-8246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1,7487TimNeudorf@cuvox.de,334-515-7487
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4,5237RafaelCardosoCosta@gustr.com,386-334-5237
6,7,female,Mary,Adams,3145 Sheila Lane,Burbank,NV,84728.0,United States,775-533-5933MaryBAdams@einrot.com,11/19/1969,146.3,65,24.3,5933MaryBAdams@einrot.com,775-533-5933
7,8,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,XiuxiuChang@einrot.com1 408 778 3236,8/13/1958,158.0,60,30.9,XiuxiuChang@einrot.com,408 778 3236
8,9,male,Dsvid,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,816-265-9578DavidGustafsson@armyspy.com,3/6/1937,163.9,66,26.5,9578DavidGustafsson@armyspy.com,816-265-9578
9,10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,SophieCabreraIbarra@teleworm.us1 718 795 9124,12/3/1930,194.7,64,33.4,SophieCabreraIbarra@teleworm.us,718 795 9124
10,11,female,Sandy,Gunnarsson,87 Wood Duck Drive,Rudyard,MI,49780.0,United States,906-478-8949SandyGunnarsson@dayrep.com,7/16/1974,199.3,62,36.4,8949SandyGunnarsson@dayrep.com,906-478-8949
11,12,male,Abdul-Nur,Isa,1092 Farm Meadow Drive,Brentwood,TN,37027.0,United States,Abdul-NurMummarIsa@rhyta.com1 931 207 0839,2/3/1954,238.7,73,31.5,NurMummarIsa@rhyta.com,931 207 0839
12,13,male,Omeokachie,Ibeamaka,2544 Worley Avenue,Lynchburg,VA,24504.0,United States,OmeokachieIbeamaka@einrot.com434-509-2614,8/5/1957,224.2,69,33.1,OmeokachieIbeamaka@einrot.com,434-509-2614
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8,AnenechiChidi@armyspy.com,+1 (205) 417-8095
14,15,female,Asia,Woźniak,4970 Heather Sees Way,Tulsa,OK,74105.0,United States,AsiaWozniak@rhyta.com918-712-3469,8/15/1997,112.0,65,18.6,AsiaWozniak@rhyta.com,918-712-3469
15,16,male,Søren,Lund,2438 Shady Pines Drive,Kingsport,VA,37660.0,United States,276-225-1955SrenFLund@gustr.com,8/23/1922,201.5,64,34.6,1955SrenFLund@gustr.com,276-225-1955
16,17,female,Tám,Liễu,2152 Heritage Road,Fresno,California,93706.0,United States,LieuThiThuTam@dayrep.com1 559 765 7836,11/14/1952,183.9,61,34.7,LieuThiThuTam@dayrep.com,559 765 7836
17,18,female,Roxanne,Andreyeva,2103 Edington Drive,Smyrna,GA,30082.0,United States,RoxanneAndreyeva@armyspy.com678-829-8578,7/24/1922,129.1,60,25.2,RoxanneAndreyeva@armyspy.com,678-829-8578
18,19,male,William,Oates,441 Tibbs Avenue,Ekalaka,MT,59324.0,United States,406-775-2696WilliamVOates@armyspy.com,9/4/1949,202.2,64,34.7,2696WilliamVOates@armyspy.com,406-775-2696
19,20,male,Zak,Kelly,994 Hill Croft Farm Road,Oroville,California,95966.0,United States,ZakKelly@rhyta.com1 530 532 8397,12/13/1988,208.8,70,30.0,ZakKelly@rhyta.com,530 532 8397
20,21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,SofiaTKarlsen@teleworm.us1 781 447 1763,9/24/1934,153.1,66,24.7,SofiaTKarlsen@teleworm.us,781 447 1763
21,22,male,Samúel,Guðbrandsson,1904 Granville Lane,Elmsford,NJ,10523.0,United States,973-445-5341SamuelGubrandsson@teleworm.us,4/12/1983,223.7,69,33.0,5341SamuelGubrandsson@teleworm.us,973-445-5341
22,23,male,Manchu,Su,1092 Deans Lane,Pleasantville,NY,10570.0,United States,914-745-6108ManchuSu@einrot.com,1/19/1936,130.7,65,21.7,6108ManchuSu@einrot.com,914-745-6108
23,24,male,Lovre,Galić,4941 Marion Drive,Winter Haven,Florida,33830.0,United States,LovreGalic@gustr.com1 813 355 9476,5/26/1960,222.9,66,36.0,LovreGalic@gustr.com,813 355 9476
24,25,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4,JakobCJakobsen@einrot.com,+1 (845) 858-7707
25,26,male,Gregor,Bole,922 Chapmans Lane,Albuquerque,NM,87109.0,United States,GregorBole@gustr.com505-828-4955,6/19/1922,180.8,67,28.3,GregorBole@gustr.com,505-828-4955
26,27,female,Ella,Lund,1207 Garfield Road,Peoria,IL,61602.0,United States,309-671-8852EllaLund@armyspy.com,12/19/1933,144.8,61,27.4,8852EllaLund@armyspy.com,309-671-8852
27,28,male,Joseph,Tucker,4982 Wood Street,Venice,LA,70091.0,United States,985-814-7603JosephNTucker@rhyta.com,4/10/1959,175.8,72,23.8,7603JosephNTucker@rhyta.com,985-814-7603
28,29,male,Robert,Wolf,2386 Linda Street,Fort Washington,PA,19034.0,United States,RobertWolf@fleckens.hu1 267 895 7462,6/26/1937,206.6,70,29.6,RobertWolf@fleckens.hu,267 895 7462
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4,JakobCJakobsen@einrot.com,+1 (845) 858-7707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,474,female,Kate,Wilkinson,664 Lyon Avenue,South Boston,MA,2127.0,United States,KateWilkinson@armyspy.com1 508 905 2371,7/18/1998,175.3,65,29.2,KateWilkinson@armyspy.com,508 905 2371
474,475,female,Esperanza,Labrosse,1370 Flint Street,Atlanta,GA,30303.0,United States,EsperanzaLabrosse@armyspy.com678-263-3564,10/7/1961,181.5,63,32.1,EsperanzaLabrosse@armyspy.com,678-263-3564
475,476,male,Malik,Vaneker,1270 Haul Road,Mountain View,California,94041.0,United States,MalikVaneker@superrito.com650-962-7179,9/25/1953,214.4,67,33.6,MalikVaneker@superrito.com,650-962-7179
476,477,female,Berta,Napolitani,1815 Garrett Street,Philadelphia,PA,19108.0,United States,267-972-3749BertaNapolitani@rhyta.com,12/2/1958,153.3,63,27.2,3749BertaNapolitani@rhyta.com,267-972-3749
477,478,male,Juliusz,Majewski,4435 Poe Road,Florence,SC,29501.0,United States,JuliuszMajewski@superrito.com+1 (843) 212-6421,9/29/1966,212.1,69,31.3,JuliuszMajewski@superrito.com,+1 (843) 212-6421
478,479,female,Edelma,Villalpando,312 Jim Rosa Lane,San Jose,CA,95134.0,United States,EdelmaVillalpandoSantillan@teleworm.us+1 (415)...,6/24/1977,109.6,63,19.4,EdelmaVillalpandoSantillan@teleworm.us,+1 (415) 755-6435
479,480,male,Tapa,Arsanukayev,4720 Gordon Street,Ontario,California,91762.0,United States,TapaArsanukayev@dayrep.com1 909 458 2515,9/15/1955,220.0,65,36.6,TapaArsanukayev@dayrep.com,909 458 2515
480,481,male,Nasser,Mansour,547 Weekley Street,San Antonio,TX,78212.0,United States,NasserMazinMansour@fleckens.hu1 210 326 5509,3/25/1938,183.5,66,29.6,NasserMazinMansour@fleckens.hu,210 326 5509
481,482,male,Michael,Kristensen,1614 Heather Sees Way,Tulsa,OK,74116.0,United States,MichaelKristensen@gustr.com1 918 706 2776,8/10/1930,154.7,65,25.7,MichaelKristensen@gustr.com,918 706 2776
482,483,male,Diogo,Souza,4033 White Avenue,Corpus Christi,TX,78401.0,United States,361-693-4960DiogoBarrosSouza@jourrapide.com,3/3/1945,220.0,65,36.6,4960DiogoBarrosSouza@jourrapide.com,361-693-4960
483,484,female,Angel,Grant,990 Melville Street,Memphis,TN,38118.0,United States,731-577-0292AngelGrant@fleckens.hu,8/14/1987,123.9,61,23.4,0292AngelGrant@fleckens.hu,731-577-0292
484,485,male,Placido,Udinesi,1094 Jones Avenue,Greensboro,NC,28716.0,United States,336-697-2005PlacidoUdinesi@dayrep.com,5/31/1934,175.8,65,29.3,2005PlacidoUdinesi@dayrep.com,336-697-2005
485,486,male,Trifon,Izmailov,3697 Drainer Avenue,Fort Walton Beach,FL,32548.0,United States,TrifonIzmailov@fleckens.hu1 850 659 0417,2/15/1973,255.9,74,32.9,TrifonIzmailov@fleckens.hu,850 659 0417
486,487,male,Samuel,Blix,3488 Clair Street,Waco,TX,76706.0,United States,254-681-4504SamuelBlix@dayrep.com,7/6/1983,211.4,74,27.1,4504SamuelBlix@dayrep.com,254-681-4504
487,488,male,Ivar,Löfgren,1346 Nicholas Street,Ottawa,KS,66067.0,United States,IvarLofgren@armyspy.com1 785 229 1188,11/7/1962,242.4,77,28.7,IvarLofgren@armyspy.com,785 229 1188
488,489,male,Mika,Martinsson,962 George Street,Ocala,Florida,34471.0,United States,352-453-4601MikaMartinsson@armyspy.com,1/27/1970,165.0,67,25.8,4601MikaMartinsson@armyspy.com,352-453-4601
489,490,female,Jasmine,Sykes,2607 Water Street,Lafayette,California,94549.0,United States,JasmineSykes@jourrapide.com925-283-5425,12/1/1988,187.2,63,33.2,JasmineSykes@jourrapide.com,925-283-5425
490,491,male,Jackson,Addison,1160 Taylor Street,New Rochelle,New York,10801.0,United States,914-636-9304JacksonAddison@armyspy.com,5/29/1953,192.7,69,28.5,9304JacksonAddison@armyspy.com,914-636-9304
491,492,female,Vanessa,Ferguson,241 Freshour Circle,San Antonio,TX,78205.0,United States,210-222-8684VanessaFerguson@jourrapide.com,9/21/1950,149.8,67,23.5,8684VanessaFerguson@jourrapide.com,210-222-8684
492,493,male,Poldi,Tar,3958 Liberty Avenue,Burbank,California,91505.0,United States,714-496-2264TarPoldi@superrito.com,5/23/1970,184.6,70,26.5,2264TarPoldi@superrito.com,714-496-2264
493,494,female,Fen,Chin,1826 Poplar Chase Lane,Boise,ID,83702.0,United States,FenChin@gustr.com+1 (208) 388-1065,3/18/1997,195.1,68,29.7,FenChin@gustr.com,+1 (208) 388-1065
494,495,female,Sirkka,Piirainen,4102 Ritter Avenue,Roseville,MI,48066.0,United States,SirkkaPiirainen@teleworm.us+1 (586) 790-0975,1/16/1942,126.3,67,19.8,SirkkaPiirainen@teleworm.us,+1 (586) 790-0975
495,496,male,Hajime,Tsukada,4111 Thunder Road,San Mateo,CA,94403.0,United States,650-570-4896HajimeTsukada@dayrep.com,9/5/1972,168.1,66,27.1,4896HajimeTsukada@dayrep.com,650-570-4896
496,497,male,Alexander,Hueber,3868 Freed Drive,Stockton,California,95204.0,United States,AlexanderHueber@jourrapide.com1 209 762 2320,9/12/1942,194.0,72,26.3,AlexanderHueber@jourrapide.com,209 762 2320
497,498,male,Masataka,Murakami,1179 Patton Lane,Tulsa,OK,74116.0,United States,MasatakaMurakami@einrot.com+1 (918) 984-9171,8/19/1937,155.1,72,21.0,MasatakaMurakami@einrot.com,+1 (918) 984-9171
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6,0579MustafaLindstrom@jourrapide.com,207-477-0579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4,4492RumanBisliev@gustr.com,928-284-4492
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8,6007JinkedeKeizer@teleworm.us,816-223-6007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,360 443 2060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3,PatrickGersten@rhyta.com,402-848-4923

In [91]:
patients_clean.drop('contact', axis=1)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone_number
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,ZoeWellish@superrito.com,951-719-9170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,PamelaSHill@cuvox.de,+1 (217) 569-3204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,2/19/1980,177.8,71,24.8,JaeMDebord@gustr.com,402-363-6804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,PhanBaLiem@jourrapide.com,+1 (732) 636-8246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,2/18/1928,192.3,27,26.1,TimNeudorf@cuvox.de,334-515-7487
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,8/31/1931,183.9,70,26.4,RafaelCardosoCosta@gustr.com,386-334-5237
6,7,female,Mary,Adams,3145 Sheila Lane,Burbank,NV,84728.0,United States,11/19/1969,146.3,65,24.3,MaryBAdams@einrot.com,775-533-5933
7,8,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,8/13/1958,158.0,60,30.9,XiuxiuChang@einrot.com,408 778 3236
8,9,male,Dsvid,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,3/6/1937,163.9,66,26.5,DavidGustafsson@armyspy.com,816-265-9578
9,10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,12/3/1930,194.7,64,33.4,SophieCabreraIbarra@teleworm.us,718 795 9124
10,11,female,Sandy,Gunnarsson,87 Wood Duck Drive,Rudyard,MI,49780.0,United States,7/16/1974,199.3,62,36.4,SandyGunnarsson@dayrep.com,906-478-8949
11,12,male,Abdul-Nur,Isa,1092 Farm Meadow Drive,Brentwood,TN,37027.0,United States,2/3/1954,238.7,73,31.5,Abdul-NurMummarIsa@rhyta.com,931 207 0839
12,13,male,Omeokachie,Ibeamaka,2544 Worley Avenue,Lynchburg,VA,24504.0,United States,8/5/1957,224.2,69,33.1,OmeokachieIbeamaka@einrot.com,434-509-2614
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,3/7/1961,228.4,67,35.8,AnenechiChidi@armyspy.com,+1 (205) 417-8095
14,15,female,Asia,Woźniak,4970 Heather Sees Way,Tulsa,OK,74105.0,United States,8/15/1997,112.0,65,18.6,AsiaWozniak@rhyta.com,918-712-3469
15,16,male,Søren,Lund,2438 Shady Pines Drive,Kingsport,VA,37660.0,United States,8/23/1922,201.5,64,34.6,SrenFLund@gustr.com,276-225-1955
16,17,female,Tám,Liễu,2152 Heritage Road,Fresno,California,93706.0,United States,11/14/1952,183.9,61,34.7,LieuThiThuTam@dayrep.com,559 765 7836
17,18,female,Roxanne,Andreyeva,2103 Edington Drive,Smyrna,GA,30082.0,United States,7/24/1922,129.1,60,25.2,RoxanneAndreyeva@armyspy.com,678-829-8578
18,19,male,William,Oates,441 Tibbs Avenue,Ekalaka,MT,59324.0,United States,9/4/1949,202.2,64,34.7,WilliamVOates@armyspy.com,406-775-2696
19,20,male,Zak,Kelly,994 Hill Croft Farm Road,Oroville,California,95966.0,United States,12/13/1988,208.8,70,30.0,ZakKelly@rhyta.com,530 532 8397
20,21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,9/24/1934,153.1,66,24.7,SofiaTKarlsen@teleworm.us,781 447 1763
21,22,male,Samúel,Guðbrandsson,1904 Granville Lane,Elmsford,NJ,10523.0,United States,4/12/1983,223.7,69,33.0,SamuelGubrandsson@teleworm.us,973-445-5341
22,23,male,Manchu,Su,1092 Deans Lane,Pleasantville,NY,10570.0,United States,1/19/1936,130.7,65,21.7,ManchuSu@einrot.com,914-745-6108
23,24,male,Lovre,Galić,4941 Marion Drive,Winter Haven,Florida,33830.0,United States,5/26/1960,222.9,66,36.0,LovreGalic@gustr.com,813 355 9476
24,25,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,8/1/1985,155.8,67,24.4,JakobCJakobsen@einrot.com,+1 (845) 858-7707
25,26,male,Gregor,Bole,922 Chapmans Lane,Albuquerque,NM,87109.0,United States,6/19/1922,180.8,67,28.3,GregorBole@gustr.com,505-828-4955
26,27,female,Ella,Lund,1207 Garfield Road,Peoria,IL,61602.0,United States,12/19/1933,144.8,61,27.4,EllaLund@armyspy.com,309-671-8852
27,28,male,Joseph,Tucker,4982 Wood Street,Venice,LA,70091.0,United States,4/10/1959,175.8,72,23.8,JosephNTucker@rhyta.com,985-814-7603
28,29,male,Robert,Wolf,2386 Linda Street,Fort Washington,PA,19034.0,United States,6/26/1937,206.6,70,29.6,RobertWolf@fleckens.hu,267 895 7462
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,8/1/1985,155.8,67,24.4,JakobCJakobsen@einrot.com,+1 (845) 858-7707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,474,female,Kate,Wilkinson,664 Lyon Avenue,South Boston,MA,2127.0,United States,7/18/1998,175.3,65,29.2,KateWilkinson@armyspy.com,508 905 2371
474,475,female,Esperanza,Labrosse,1370 Flint Street,Atlanta,GA,30303.0,United States,10/7/1961,181.5,63,32.1,EsperanzaLabrosse@armyspy.com,678-263-3564
475,476,male,Malik,Vaneker,1270 Haul Road,Mountain View,California,94041.0,United States,9/25/1953,214.4,67,33.6,MalikVaneker@superrito.com,650-962-7179
476,477,female,Berta,Napolitani,1815 Garrett Street,Philadelphia,PA,19108.0,United States,12/2/1958,153.3,63,27.2,BertaNapolitani@rhyta.com,267-972-3749
477,478,male,Juliusz,Majewski,4435 Poe Road,Florence,SC,29501.0,United States,9/29/1966,212.1,69,31.3,JuliuszMajewski@superrito.com,+1 (843) 212-6421
478,479,female,Edelma,Villalpando,312 Jim Rosa Lane,San Jose,CA,95134.0,United States,6/24/1977,109.6,63,19.4,EdelmaVillalpandoSantillan@teleworm.us,+1 (415) 755-6435
479,480,male,Tapa,Arsanukayev,4720 Gordon Street,Ontario,California,91762.0,United States,9/15/1955,220.0,65,36.6,TapaArsanukayev@dayrep.com,909 458 2515
480,481,male,Nasser,Mansour,547 Weekley Street,San Antonio,TX,78212.0,United States,3/25/1938,183.5,66,29.6,NasserMazinMansour@fleckens.hu,210 326 5509
481,482,male,Michael,Kristensen,1614 Heather Sees Way,Tulsa,OK,74116.0,United States,8/10/1930,154.7,65,25.7,MichaelKristensen@gustr.com,918 706 2776
482,483,male,Diogo,Souza,4033 White Avenue,Corpus Christi,TX,78401.0,United States,3/3/1945,220.0,65,36.6,DiogoBarrosSouza@jourrapide.com,361-693-4960
483,484,female,Angel,Grant,990 Melville Street,Memphis,TN,38118.0,United States,8/14/1987,123.9,61,23.4,AngelGrant@fleckens.hu,731-577-0292
484,485,male,Placido,Udinesi,1094 Jones Avenue,Greensboro,NC,28716.0,United States,5/31/1934,175.8,65,29.3,PlacidoUdinesi@dayrep.com,336-697-2005
485,486,male,Trifon,Izmailov,3697 Drainer Avenue,Fort Walton Beach,FL,32548.0,United States,2/15/1973,255.9,74,32.9,TrifonIzmailov@fleckens.hu,850 659 0417
486,487,male,Samuel,Blix,3488 Clair Street,Waco,TX,76706.0,United States,7/6/1983,211.4,74,27.1,SamuelBlix@dayrep.com,254-681-4504
487,488,male,Ivar,Löfgren,1346 Nicholas Street,Ottawa,KS,66067.0,United States,11/7/1962,242.4,77,28.7,IvarLofgren@armyspy.com,785 229 1188
488,489,male,Mika,Martinsson,962 George Street,Ocala,Florida,34471.0,United States,1/27/1970,165.0,67,25.8,MikaMartinsson@armyspy.com,352-453-4601
489,490,female,Jasmine,Sykes,2607 Water Street,Lafayette,California,94549.0,United States,12/1/1988,187.2,63,33.2,JasmineSykes@jourrapide.com,925-283-5425
490,491,male,Jackson,Addison,1160 Taylor Street,New Rochelle,New York,10801.0,United States,5/29/1953,192.7,69,28.5,JacksonAddison@armyspy.com,914-636-9304
491,492,female,Vanessa,Ferguson,241 Freshour Circle,San Antonio,TX,78205.0,United States,9/21/1950,149.8,67,23.5,VanessaFerguson@jourrapide.com,210-222-8684
492,493,male,Poldi,Tar,3958 Liberty Avenue,Burbank,California,91505.0,United States,5/23/1970,184.6,70,26.5,TarPoldi@superrito.com,714-496-2264
493,494,female,Fen,Chin,1826 Poplar Chase Lane,Boise,ID,83702.0,United States,3/18/1997,195.1,68,29.7,FenChin@gustr.com,+1 (208) 388-1065
494,495,female,Sirkka,Piirainen,4102 Ritter Avenue,Roseville,MI,48066.0,United States,1/16/1942,126.3,67,19.8,SirkkaPiirainen@teleworm.us,+1 (586) 790-0975
495,496,male,Hajime,Tsukada,4111 Thunder Road,San Mateo,CA,94403.0,United States,9/5/1972,168.1,66,27.1,HajimeTsukada@dayrep.com,650-570-4896
496,497,male,Alexander,Hueber,3868 Freed Drive,Stockton,California,95204.0,United States,9/12/1942,194.0,72,26.3,AlexanderHueber@jourrapide.com,209 762 2320
497,498,male,Masataka,Murakami,1179 Patton Lane,Tulsa,OK,74116.0,United States,8/19/1937,155.1,72,21.0,MasatakaMurakami@einrot.com,+1 (918) 984-9171
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,4/10/1959,181.1,72,24.6,MustafaLindstrom@jourrapide.com,207-477-0579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,3/26/1948,239.6,70,34.4,RumanBisliev@gustr.com,928-284-4492
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,1/13/1971,171.2,67,26.8,JinkedeKeizer@teleworm.us,816-223-6007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,2/13/1952,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,360 443 2060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,5/3/1954,138.2,71,19.3,PatrickGersten@rhyta.com,402-848-4923

In [92]:
# test emai;s by checking the email column doesn't start with a number or + (sort by values will reveal this)

patients_clean.email.sort_values()

404                 AaliyahRice@dayrep.com
11            Abdul-NurMummarIsa@rhyta.com
332                  AbelEfrem@fleckens.hu
258                AbelYonatan@teleworm.us
305      AddolorataLombardi@jourrapide.com
118           AdibMutazzGhanem@fleckens.hu
420                AdlanShishani@gustr.com
238          AkselHVestergaard@armyspy.com
61                    AlanMilne@dayrep.com
130            AlbertRWolfe@jourrapide.com
409          AlbikaIbragimov@superrito.com
196             AlbinaZetticci@teleworm.us
37                AlbincaKomavec@rhyta.com
295            AlbinoSchiavone@fleckens.hu
276                AlexCrawford@dayrep.com
70       AlexanderEMathiesen@superrito.com
496         AlexanderHueber@jourrapide.com
56            AlissaMontezFranco@gustr.com
172              AlvinAJackson@armyspy.com
437              AlwinSvensson@armyspy.com
358          AmalieJChristensen@einrot.com
143    AmandaCavalcantiRibeiro@fleckens.hu
47               AnaSousaCorreia@rhyta.com
442     AnaniasEnriquezMontoya@armyspy.com
55                        AncoPak@cuvox.de
81                    AndreNordin@cuvox.de
466              AndreaBrodahl@armyspy.com
13               AnenechiChidi@armyspy.com
483                 AngelGrant@fleckens.hu
233             AngelaLavrentyev@gustr.com
                      ...
389              YegorUspensky@fleckens.hu
63             YukitakaTakenaka@einrot.com
181               YumenaNakayama@gustr.com
114             YunadiBarsukov@teleworm.us
19                      ZakKelly@rhyta.com
73                  ZarkaRap@superrito.com
199             ZdenekSynek@jourrapide.com
456      ZikoranaudodimmaChinedum@cuvox.de
165                ZlatkoRukavina@cuvox.de
0                 ZoeWellish@superrito.com
49                ZsinkoVivien@teleworm.us
244                      johndoe@email.com
237                      johndoe@email.com
229                      johndoe@email.com
215                      johndoe@email.com
277                      johndoe@email.com
251                      johndoe@email.com
265          orunnTryggvadottir@dayrep.com
209                                    NaN
219                                    NaN
230                                    NaN
234                                    NaN
242                                    NaN
249                                    NaN
257                                    NaN
264                                    NaN
269                                    NaN
278                                    NaN
286                                    NaN
296                                    NaN
Name: email, Length: 503, dtype: object